" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim

set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim
try
  source ~/.vim_runtime/my_configs.vim
catch
endtry
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'The-NERD-tree' " Vim 에서 파일 탐색기 사용 
let NERDTreeWinPos = "left"
nmap <F7> : NERDTree<CR>
Plugin 'AutoComplPop' " VIM 자동완성기능(Ctrl+P) 
Plugin 'vim-airline/vim-airline' 
Plugin 'vim-airline/vim-airline-themes' 
let g:airline#extensions#tabline#enabled = 1 
let g:airline#extensions#tabline#left_sep = ' ' 
let g:airline#extensions#tabline#left_alt_sep = '|' 
let g:airline_theme='papercolor'
Plugin 'Tagbar' 
nmap <F8> :TagbarToggle<CR> 
Plugin 'togglenumber' 
nmap <F5> :ToggleNumber<CR>
Plugin 'airblade/vim-gitgutter' " 코드 변경 내역을 한눈에 
Plugin 'tpope/vim-fugitive' " Vim에서 Git 사용하기 
Plugin 'scrooloose/syntastic' " 코드 문법 체크 
Plugin 'ctrlpvim/ctrlp.vim' " 파일 찾기 기능 (사용법 : Control + P)p
call vundle#end()
"set tags=/Users/hbw/px4/PX4-Autopilot/tags,/Users/hbw/px4/mavesp8266/tags,/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/tags,/Library/Developer/CommandLineTools/usr/include/c++/tags  
"set tags=/Users/hbw/px4/mavesp8266/tags,/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/tags,/Library/Developer/CommandLineTools/usr/include/c++/tags  
"set tags=/Users/hbw/study/tags-kernel 
set tags=/Users/hbw/study/tags 




